begin;

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  customer_type text not null default 'individual' check (customer_type in ('individual','company','institution')),
  name text not null,
  company_name text,
  phone text,
  whatsapp text,
  email text,
  city text,
  address text,
  source text not null default 'direct' check (source in ('website','whatsapp','referral','direct','social','other')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists customers_phone_unique_nonempty on public.customers (phone) where phone is not null and phone <> '';
create index if not exists customers_name_search_idx on public.customers using gin (to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(company_name,'')));

create table if not exists public.customer_activities (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  activity_type text not null default 'follow_up' check (activity_type in ('call','whatsapp','meeting','email','follow_up','note')),
  subject text not null,
  details text,
  due_at timestamptz,
  completed_at timestamptz,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.operational_projects (
  id uuid primary key default gen_random_uuid(),
  project_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  source_quote_id text references public.quotes(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'open' check (status in ('open','awaiting_approval','approved','in_design','in_production','quality_check','ready_for_delivery','delivered','closed','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  owner_id uuid references public.profiles(id) on delete set null,
  start_date date,
  due_date date,
  delivered_at timestamptz,
  estimated_total numeric(14,2) not null default 0 check (estimated_total >= 0),
  actual_cost numeric(14,2) not null default 0 check (actual_cost >= 0),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists operational_projects_status_due_idx on public.operational_projects(status, due_date);
create index if not exists operational_projects_customer_idx on public.operational_projects(customer_id);

create table if not exists public.commercial_quotes (
  id uuid primary key default gen_random_uuid(),
  quote_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  project_id uuid references public.operational_projects(id) on delete set null,
  source_quote_id text references public.quotes(id) on delete set null,
  version integer not null default 1 check (version > 0),
  status text not null default 'draft' check (status in ('draft','sent','approved','rejected','expired','converted')),
  currency text not null default 'YER',
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  discount numeric(14,2) not null default 0 check (discount >= 0),
  tax numeric(14,2) not null default 0 check (tax >= 0),
  total numeric(14,2) generated always as (greatest(0, subtotal - discount + tax)) stored,
  valid_until date,
  terms text,
  line_items jsonb not null default '[]'::jsonb,
  sent_at timestamptz,
  approved_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists commercial_quotes_customer_idx on public.commercial_quotes(customer_id);
create index if not exists commercial_quotes_status_idx on public.commercial_quotes(status);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  project_id uuid references public.operational_projects(id) on delete set null,
  commercial_quote_id uuid references public.commercial_quotes(id) on delete set null,
  status text not null default 'issued' check (status in ('draft','issued','partially_paid','paid','overdue','void')),
  currency text not null default 'YER',
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  discount numeric(14,2) not null default 0 check (discount >= 0),
  tax numeric(14,2) not null default 0 check (tax >= 0),
  total numeric(14,2) generated always as (greatest(0, subtotal - discount + tax)) stored,
  due_date date,
  issued_at timestamptz not null default now(),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists invoices_customer_idx on public.invoices(customer_id);
create index if not exists invoices_project_idx on public.invoices(project_id);
create index if not exists invoices_status_due_idx on public.invoices(status,due_date);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  method text not null default 'cash' check (method in ('cash','bank_transfer','card','wallet','other')),
  reference text,
  received_at timestamptz not null default now(),
  notes text,
  received_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists payments_invoice_idx on public.payments(invoice_id);

create table if not exists public.production_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  project_id uuid not null references public.operational_projects(id) on delete restrict,
  source_design_task_id text,
  status text not null default 'queued' check (status in ('queued','prepress','printing','finishing','assembly','quality_check','ready','delivered','on_hold','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_to uuid references public.profiles(id) on delete set null,
  due_date date,
  specifications jsonb not null default '{}'::jsonb,
  quality_notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists production_orders_status_due_idx on public.production_orders(status,due_date);

create table if not exists public.production_stages (
  id uuid primary key default gen_random_uuid(),
  production_order_id uuid not null references public.production_orders(id) on delete cascade,
  name text not null,
  status text not null default 'pending' check (status in ('pending','in_progress','blocked','completed','skipped')),
  assigned_to uuid references public.profiles(id) on delete set null,
  due_date date,
  sort_order integer not null default 0,
  notes text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists production_stages_order_idx on public.production_stages(production_order_id,sort_order);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_name text,
  phone text,
  email text,
  address text,
  payment_terms text,
  lead_time_days integer check (lead_time_days is null or lead_time_days >= 0),
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  sku text unique,
  name text not null,
  category text,
  unit text not null default 'قطعة',
  quantity numeric(14,3) not null default 0,
  reorder_level numeric(14,3) not null default 0,
  average_unit_cost numeric(14,2) not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (quantity >= 0),
  check (reorder_level >= 0),
  check (average_unit_cost >= 0)
);

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  inventory_item_id uuid not null references public.inventory_items(id) on delete restrict,
  movement_type text not null check (movement_type in ('receipt','issue','return','adjustment')),
  quantity numeric(14,3) not null check (quantity > 0),
  unit_cost numeric(14,2) not null default 0 check (unit_cost >= 0),
  project_id uuid references public.operational_projects(id) on delete set null,
  supplier_id uuid references public.suppliers(id) on delete set null,
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists inventory_movements_item_idx on public.inventory_movements(inventory_item_id,created_at desc);
create trigger rawaj_apply_inventory_movement after insert on public.inventory_movements for each row execute function private.apply_rawaj_inventory_movement();
create trigger rawaj_refresh_invoice_after_payment after insert or update or delete on public.payments for each row execute function private.refresh_rawaj_invoice_status();

create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  purchase_number bigint generated by default as identity unique,
  supplier_id uuid not null references public.suppliers(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft','ordered','partially_received','received','cancelled')),
  ordered_at timestamptz,
  expected_at date,
  total numeric(14,2) not null default 0 check (total >= 0),
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated always as identity primary key,
  entity_table text not null,
  entity_id text not null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  actor_id uuid references auth.users(id) on delete set null,
  before_data jsonb,
  after_data jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists audit_events_entity_idx on public.audit_events(entity_table,entity_id,occurred_at desc);
create index if not exists audit_events_actor_idx on public.audit_events(actor_id,occurred_at desc);

create or replace function private.capture_rawaj_audit_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  old_row jsonb;
  new_row jsonb;
  row_id text;
begin
  if tg_op = 'INSERT' then
    new_row := to_jsonb(new);
    row_id := coalesce(new_row->>'id', new_row->>'invoice_number', new_row->>'project_number', new_row->>'quote_number', new_row->>'order_number', new_row->>'purchase_number');
  elsif tg_op = 'UPDATE' then
    old_row := to_jsonb(old);
    new_row := to_jsonb(new);
    row_id := coalesce(new_row->>'id', old_row->>'id');
  else
    old_row := to_jsonb(old);
    row_id := old_row->>'id';
  end if;
  insert into public.audit_events(entity_table,entity_id,action,actor_id,before_data,after_data)
  values (tg_table_name, coalesce(row_id,'unknown'), tg_op, auth.uid(), old_row, new_row);
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$;

create or replace function private.apply_rawaj_inventory_movement()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $
declare
  delta numeric(14,3);
begin
  delta := case
    when new.movement_type in ('receipt','return','adjustment') then new.quantity
    when new.movement_type = 'issue' then -new.quantity
    else 0
  end;

  update public.inventory_items
  set quantity = quantity + delta,
      average_unit_cost = case
        when new.movement_type = 'receipt' and quantity + delta > 0
          then ((quantity * average_unit_cost) + (new.quantity * new.unit_cost)) / (quantity + delta)
        else average_unit_cost
      end,
      updated_at = now()
  where id = new.inventory_item_id
    and quantity + delta >= 0;

  if not found then
    raise exception 'Insufficient inventory or item not found; movement was not recorded.';
  end if;

  return new;
end;
$;

create or replace function private.refresh_rawaj_invoice_status()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $
declare
  invoice_id_value uuid;
  invoice_total numeric(14,2);
  paid_total numeric(14,2);
  due_date_value date;
  current_status text;
begin
  if tg_op = 'DELETE' then
    invoice_id_value := old.invoice_id;
  else
    invoice_id_value := new.invoice_id;
  end if;
  select total, due_date, status into invoice_total, due_date_value, current_status
  from public.invoices where id = invoice_id_value;

  if not found or current_status in ('draft','void') then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  select coalesce(sum(amount),0) into paid_total
  from public.payments where invoice_id = invoice_id_value;

  update public.invoices
  set status = case
    when paid_total >= invoice_total then 'paid'
    when paid_total > 0 then 'partially_paid'
    when due_date_value is not null and due_date_value < current_date then 'overdue'
    else 'issued'
  end,
  updated_at = now()
  where id = invoice_id_value;

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$;

revoke all on function private.capture_rawaj_audit_event() from public, anon, authenticated;

do $$
declare
  t text;
begin
  foreach t in array array[
    'customers','customer_activities','operational_projects','commercial_quotes','invoices',
    'payments','production_orders','production_stages','suppliers','inventory_items',
    'inventory_movements','purchase_orders','audit_events'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'customers','customer_activities','operational_projects','commercial_quotes','invoices',
    'payments','production_orders','production_stages','suppliers','inventory_items',
    'inventory_movements','purchase_orders'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_staff_read', t);
    execute format('create policy %I on public.%I for select to authenticated using (private.has_any_role(array[''owner'',''admin'',''sales'',''designer'']))', t || '_staff_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_staff_insert', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (private.has_any_role(array[''owner'',''admin'',''sales'']))', t || '_staff_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_staff_update', t);
    execute format('create policy %I on public.%I for update to authenticated using (private.has_any_role(array[''owner'',''admin'',''sales''])) with check (private.has_any_role(array[''owner'',''admin'',''sales'']))', t || '_staff_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_staff_delete', t);
    execute format('create policy %I on public.%I for delete to authenticated using (private.has_any_role(array[''owner'',''admin'']))', t || '_staff_delete', t);
    execute format('drop trigger if exists rawaj_audit_capture on public.' || quote_ident(t));
    execute format('create trigger rawaj_audit_capture after insert or update or delete on public.%I for each row execute function private.capture_rawaj_audit_event()', t);
  end loop;
end $$;

drop policy if exists audit_events_staff_read on public.audit_events;
create policy audit_events_staff_read on public.audit_events for select to authenticated
using (private.has_any_role(array['owner','admin']));
drop policy if exists audit_events_no_direct_write on public.audit_events;
create policy audit_events_no_direct_write on public.audit_events for all to authenticated
using (false) with check (false);

grant select, insert, update, delete on public.customers, public.customer_activities, public.operational_projects,
  public.commercial_quotes, public.invoices, public.payments, public.production_orders, public.production_stages,
  public.suppliers, public.inventory_items, public.inventory_movements, public.purchase_orders to authenticated;
grant select on public.audit_events to authenticated;
grant usage, select on sequence public.operational_projects_project_number_seq to authenticated;
grant usage, select on sequence public.commercial_quotes_quote_number_seq to authenticated;
grant usage, select on sequence public.invoices_invoice_number_seq to authenticated;
grant usage, select on sequence public.production_orders_order_number_seq to authenticated;
grant usage, select on sequence public.purchase_orders_purchase_number_seq to authenticated;
grant usage, select on sequence public.audit_events_id_seq to authenticated;

commit;
